spring.application.name=expense-tracker

# Mysql connection
spring.datasource.url=jdbc:mysql://localhost:3306/expenseTracker
spring.datasource.username=root
spring.datasource.password=Ammar

# JPA / Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.thymeleaf.cache=false
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
spring.web.resources.cache.period=0
